### PR TITLE
Update Test of Chapter2.hs

### PR DESCRIPTION
**Pull request by pro2s**
Fix typo in the Test description for task 12*

cc @vrom911 @chshersh

### CODE REVIEW

**Review by vrom911 — COMMENTED** [review]
Hey @pro2s ! Nice catch!

Though, we won't be able to accept this, as this has the answers for Chapter 1 😄 
Could you Amend this commit with only test file change?

**Comment by pro2s** [comment]
> Hey @pro2s ! Nice catch!
> 
> Though, we won't be able to accept this, as this has the answers for Chapter 1 😄
> Could you Amend this commit with only test file change?

My bad, I will create a branch and update the PR

**Comment by pro2s** [comment]
@vrom911, Fixed, I reverted my `master` to correct state.

**Review by vrom911 — APPROVED** [review]
Great! Thank you so much 🤗

**Pull request merged**
